default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_development
  username: postgres
  password: steph

test:
  <<: *default
  database: blog_test
  username: postgres
  password: steph

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
